function config = GOCNMF_terminal_validation_config_R2009a
% Locked configuration for the six-dataset terminal validation.

config.dataset_names = { ...
    'COIL20','COIL100','MNIST','Optdigits','PIE','YaleB'};

config.dataset_aliases = { ...
    {'COIL20_Obj.mat','COIL20.mat','coil20.mat'}, ...
    {'COIL100_Obj.mat','COIL100.mat','coil100.mat'}, ...
    {'MNIST.mat','mnist.mat','MNIST_7000.mat'}, ...
    {'Optdigits_Han.mat','Optdigits.mat','optdigits.mat'}, ...
    {'PIE.mat','CMU_PIE.mat','PIE_Han.mat','cmu_pie.mat'}, ...
    {'YaleB.mat','ExtendedYaleB.mat','yaleB.mat'}};

% Published GOCNMF settings.
config.p_values = [3,3,4,4,3,2];
config.alpha_values = [10,10,10,10,1000,1000];

config.seeds = 20260617:20260636;
config.label_fraction = 0.10;
config.max_iterations = 50;
config.graph_block_size = 256;
config.num_controls = 3;
config.low_score_fraction = 0.20;

config.eps0 = 1e-12;
config.objective_tolerance = 1e-10;

config.condition_names = { ...
    'BASE', ...
    'REMOVE_WRONG_LU', ...
    'REMOVE_WRONG_UU', ...
    'REMOVE_WRONG_ALL', ...
    'CTRL_CORRECT_LU_1', ...
    'CTRL_CORRECT_LU_2', ...
    'CTRL_CORRECT_LU_3', ...
    'CTRL_CORRECT_UU_1', ...
    'CTRL_CORRECT_UU_2', ...
    'CTRL_CORRECT_UU_3', ...
    'CTRL_CORRECT_ALL_1', ...
    'CTRL_CORRECT_ALL_2', ...
    'CTRL_CORRECT_ALL_3'};

end
